// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz_CNsmJ_ee_Ub1ePdPjadamSreFDt_d4',
    appId: '1:597321369022:web:fa13fbe9e700eff35f25ef',
    messagingSenderId: '597321369022',
    projectId: 'jr-csp',
    authDomain: 'jr-csp.firebaseapp.com',
    storageBucket: 'jr-csp.firebasestorage.app',
    measurementId: 'G-8WG4QKK5SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1uL3swWgF5sDLlk9txIqSG6uotbCuUrM',
    appId: '1:597321369022:android:cbf39a0890840e925f25ef',
    messagingSenderId: '597321369022',
    projectId: 'jr-csp',
    storageBucket: 'jr-csp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0J7JGZ5ZzwwTDhJThkGS5J0zad_PzjXw',
    appId: '1:597321369022:ios:b8b2596854c503935f25ef',
    messagingSenderId: '597321369022',
    projectId: 'jr-csp',
    storageBucket: 'jr-csp.firebasestorage.app',
    iosBundleId: 'com.example.cspJr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0J7JGZ5ZzwwTDhJThkGS5J0zad_PzjXw',
    appId: '1:597321369022:ios:b8b2596854c503935f25ef',
    messagingSenderId: '597321369022',
    projectId: 'jr-csp',
    storageBucket: 'jr-csp.firebasestorage.app',
    iosBundleId: 'com.example.cspJr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz_CNsmJ_ee_Ub1ePdPjadamSreFDt_d4',
    appId: '1:597321369022:web:2609933b01ed2b0e5f25ef',
    messagingSenderId: '597321369022',
    projectId: 'jr-csp',
    authDomain: 'jr-csp.firebaseapp.com',
    storageBucket: 'jr-csp.firebasestorage.app',
    measurementId: 'G-KDH2CDNXTF',
  );
}
